version: "3.7"

volumes:
  bimdata:

services:
    bimserver:
      restart: always
      build : .
      container_name: bimserver
      volumes:
       - "bimdata:/var/bimserver/home"

      networks:
      - frontend
      ports:
      - "8085:8080"
      labels:
      - "traefik.enable=false"

networks:
    frontend:
       external:
           name: outside
